### ISSUE TITLE
UIWebView with inline YouTube Videos

### ISSUE THREAD

**Issue by pocketwod** [thedarkbark/NAModalSheet#18]
Hello,

Thanks for making this great framework. When I present a sheet with a uiwebview containing a youtube iframe when played the MPMoviePlayerController is unable to get in front of the sheet and plays behind it, any idea how I might fix this?

**Comment by thedarkbark** [comment]
An NAModalSheet is presented in another window in front of the previous one. The original intent was for such a sheet to be temporary and presentation of other content atop it wasn't anticipated. Perhaps you could work around it by setting the sheet's window's alpha to zero when the MPMoviePlayerController's view is presented and restore it when the movie controller is dismissed?

**Comment by pocketwod** [comment]
Ok, thank you for the suggestion. I realize its out of the intended scope so I just moved it to a UIViewController presented modally.

Thanks again.
